spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/push
    username: root
    password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
        format_sql: true
        use_sql_comments: true
    database: mysql